config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#top'
  get 'tasks/top'
  get 'tasks/index'
  get 'tasks/show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :jobs
  resources :users, except: [:index]
  devise_for :callers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caller.rb
class Caller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :salary
    validates :working_hours
    validates :place
    validates :catch
  end

  validates :catch, length: { maximum: 30 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_users
  
  private
  
  def current_users
    @current_users ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  def login_required
    redirect_to login_path unless current_users
  end

  def forbid_login_user
    if current_users
      flash[:notice] = "すでにログインしています"
      redirect_to jobs_path
    end
  end

  def ensure_correct_user
    if current_users.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to users_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :login_required, except: [:show]
  before_action :set_job, only: [:edit, :update, :destroy]
  def index
    @jobs = current_users.jobs
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_users.jobs.new(job_params)

    if @job.save
      redirect_to @job, notice: "求人「#{@job.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @job.update!(job_params)
    redirect_to jobs_url, notice: "求人「#{@job.name}」を更新しました"
  end

  def destroy
    @job.destroy
    redirect_to jobs_url, notice: "求人「#{@job.name}」を削除しました。"
  end

  private

  def job_params
    params.require(:job).permit(:name, :salary, :working_hours, :place, :feature, :catch)
  end

  def set_job
    @job = current_users.jobs.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :forbid_login_user, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to jobs_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    #.require(:session)削除
    params.permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :forbid_login_user, only: [:top]
  def top
    @jobs = Job.all
  end

  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:show]
  #不要
  #def index
    #@users = current_users
  #end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to jobs_path, notice: "ユーザー「#{@user.name}」を登録しました"
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to show, notice: "ユーザー「#{@user.name}」を更新しました"
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "ユーザー「#{@user.name}」を削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :company, :business)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :caller
  end
     
  def resource
    @resource ||= Caller.new
  end
     
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:caller]
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.slim
- if job.errors.present?
  ul#error_explanation
    - job.errors.full_messages.each do |message|
      li= message

= form_with model: job, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'job_name'
  .form-group
    = f.label :salary
    = f.text_field :salary, class: 'form-control', id: 'job_salary'
  .form-group
    = f.label :working_hours
    = f.text_field :working_hours, class: 'form-control', id: 'working_hours'
  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control', id: 'job_place'
  .form-group
    = check_box_tag :feature
    = label_tag :feature, "未経験者歓迎"
  .form-group
    = f.label :catch
    = f.text_area :catch, rows: 5, class: 'form-control', id: 'job_catch'
  = f.submit nil, class: 'btn btn-primary'

app/views/jobs/edit.html.slim
h1 求人の編集

.nav.justify-content-end
  = link_to '一覧', jobs_path, class: 'nav-link'

= render partial: 'form', locals: { job: @job }

app/views/jobs/index.html.slim
h1 登録している求人

= link_to '新規作成', new_job_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Job.human_attribute_name(:name)
      th= Job.human_attribute_name(:created_at)
      th
  tbody
    - @jobs.each do |job|
      tr
        td= link_to job.name, job
        td= job.created_at
        td
          = link_to '編集', edit_job_path(job), class: 'btn btn-primary mr-3'
          = link_to '削除', job, method: :delete, data: { confirm: "求人「#{job.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/jobs/new.html.slim
h1 求人の新規登録

.nav.justify-content-end
  = link_to '一覧', jobs_path, class: 'nav-link'

= render partial: 'form', locals: { job: @job }

app/views/jobs/show.html.slim
h1 求人の詳細

.nav.justify-content-end
  = link_to '一覧', jobs_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Job.human_attribute_name(:id)
      td= @job.id
    tr
      th= Job.human_attribute_name(:name)
      td= @job.name
    tr
      th= Job.human_attribute_name(:salary)
      td= @job.salary
    tr
      th= Job.human_attribute_name(:working_hours)
      td= @job.working_hours
    tr
      th= Job.human_attribute_name(:place)
      td= @job.place
    tr
      th= Job.human_attribute_name(:feature)
      td= @job.feature
    tr
      th= Job.human_attribute_name(:catch)
      td= @job.catch

= link_to '編集', edit_job_path, class: 'btn btn-primary mr-3' if current_users
= link_to '削除', @job, method: :delete, data: { confirm: "求人「#{@job.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' if current_users

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Recruit
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-dark.bg-dark
      .navbar-brand
        = link_to 'town work', '/'
      
      - if current_users
        ul.navbar-nav.ml-auto
          li.nav-item= link_to '求人一覧', jobs_path, class: 'nav-link'
          li.nav-item= link_to '登録企業', current_users, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
      - elsif caller_signed_in?
        ul.navbar-nav.ml-auto
          li.nav-item= link_to '求人一覧', jobs_path, class: 'nav-link'
          li.nav-item= link_to 'プロフィール変更', edit_caller_registration_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', destroy_caller_session_path, method: :delete, class: 'nav-link'
      - else
        ul
          div.row
            div.col-6.bgred
              div.row
                div.col-6.bgred
                  p.logincolor
                    |
                      一般会員
                div.col-6.bgred
                  p.lead= link_to '求人に応募をご希望の方', new_caller_registration_path
              = render :partial => "devise/sessions/login"
            div.col-6.bgred
              div.row
                div.col-6.bgred
                  p.logincolor
                    |
                      求人会員
                div.col-6.bgred
                  p.lead= link_to '求人の掲載をご希望の方', new_user_path
              = render :partial => "sessions/login"
    .container
      -if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/tasks/index.html.slim
h1 Tasks#index
p Find me in app/views/tasks/index.html.slim

app/views/tasks/top.html.slim
table.table.table-hover
 thead.thead-default
  tr
    th= Job.human_attribute_name(:name)
    th= Job.human_attribute_name(:place)
    th= Job.human_attribute_name(:salary)
    th= Job.human_attribute_name(:working_hours)
  tbody
    - @jobs.each do |job|
      .jobshow
        tr
          td= link_to job.name, job
          td= job.place
          td= job.salary
          td= job.working_hours

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, 'アカウント名'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.text_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    = f.label :company, '会社名'
    = f.text_field :company, class: 'form-control'
  .form-group
    = f.label :business, '事業内容'
    = f.text_field :business, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
<%#　不要　%>
h1 ユーザー一覧

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    
      tr
        td= link_to @users.name, @users
        td= @users.email
        td= @users.created_at
        td= @users.updated_at
        td
          = link_to '編集', edit_user_path(@users), class: 'btn btn-primary mr-3'
          = link_to '削除', @users, method: :delete, data: { confirm: "ユーザ「#{@users.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/users/new.html.slim
h1 会員登録(企業向け)

= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1 ユーザの詳細

table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:company)
      td= @user.company
    tr
      th= User.human_attribute_name(:business)
      td= @user.business

= link_to '編集', edit_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', @user, method: :delete, data: { confirm: "ユーザ「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'